import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ConditionalFooter from "@/components/ConditionalFooter";
import TransitionProvider from "@/components/animations/TransitionProvider";
import ConditionalHeader from "@/components/ConditionalHeader";
import CookieConsent from "@/components/CookieConsent";
import TrackingPixels from "@/components/TrackingPixels";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <TransitionProvider>
          <ConditionalHeader />
          <main className="flex-grow">{children}</main>
          <ConditionalFooter />
          <CookieConsent />
          <TrackingPixels />
        </TransitionProvider>
      </body>
    </html>
  );
}
