import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer"; // Import the Footer component
import { headers } from 'next/headers';
import TransitionProvider from "@/components/animations/TransitionProvider";
import ConditionalHeader from "@/components/ConditionalHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hdrs = headers();
  const path = hdrs.get('x-invoke-path') || '';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <TransitionProvider>
          <ConditionalHeader />
          <main className="flex-grow">{children}</main>
          {!path.startsWith('/admin') && <Footer />}
        </TransitionProvider>
      </body>
    </html>
  );
}
