import type { Metadata } from "next";
import { Poppins, Lato } from "next/font/google";
import "./globals.css";
import ConditionalFooter from "@/components/ConditionalFooter";
import TransitionProvider from "@/components/animations/TransitionProvider";
import ConditionalHeader from "@/components/ConditionalHeader";
import CookieConsent from "@/components/CookieConsent";
import TrackingPixels from "@/components/TrackingPixels";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    'material-symbols': 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${poppins.variable} ${lato.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <TransitionProvider>
          <ConditionalHeader />
          <main className="flex-grow">{children}</main>
          <ConditionalFooter />
          <CookieConsent />
          <TrackingPixels />
        </TransitionProvider>
      </body>
    </html>
  );
}
